# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
        migrations.AddField(
            model_name='comments',
            name='hotelCommented',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hoteles.Hotels'),
        ),
    ]
